### ISSUE TITLE
No puedo reproducir canciones

### ISSUE THREAD

**Issue by MarthexPS** [ElG3neral/Discord-Bot#1]
Configure y todo el bot, y si se activa y incluso entra al canal de voz, pero no reproduce nada y en la terminal me marca error, si me ayudan a arreglar esto se lo agradeceria

**Comment by MkevinF** [comment]
> Configure y todo el bot, y si se activa y incluso entra al canal de voz, pero no reproduce nada y en la terminal me marca error, si me ayudan a arreglar esto se lo agradeceria

Me podrías enviar que dice el terminal, recuerda que también debes seguir los pasos que dice en el Readme para poder usarlo.

**Comment by MarthexPS** [comment]
![image](https://github.com/MkevinF/Discord-Bot/assets/165730437/b79bb1eb-34cd-4f31-996b-b0d2b8cfb475)

**Comment by MkevinF** [comment]
> ![image](https://private-user-images.githubusercontent.com/165730437/318597349-b79bb1eb-34cd-4f31-996b-b0d2b8cfb475.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMTY2ODgsIm5iZiI6MTcxMjAxNjM4OCwicGF0aCI6Ii8xNjU3MzA0MzcvMzE4NTk3MzQ5LWI3OWJiMWViLTM0Y2QtNGYzMS05OTZiLWIwZDJiOGNmYjQ3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMlQwMDA2MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMDg2MjEyM2RjOGVkYzkzNzA5ZjI4ZTYxM2NjYTU4YmZlZDBiMjUzYzg5NTU3ZjRmZTU3OTQwYjc1OTFiZDg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7Hou5W2XrwH1Jz5Cpafl3_Qs9da6UrkBZQYXkMCn5L8)

Sigue estas instrucciones, no lo has seguido. 
![SS](https://github.com/MkevinF/Discord-Bot/assets/116234478/966ca2a0-a218-40f5-b53a-e3d2852fab9a)

**Comment by MarthexPS** [comment]
gracias ya vi mi error

**Comment by MkevinF** [comment]
> gracias ya vi mi error

Bien, ya te funciona todo?
